language: rust

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: 1.32.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - name: rustfmt/clippy
      rust: stable
      install:
        - rustup component add rustfmt clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all --all-targets

cache: cargo

script:
  - cargo build --all-features --verbose -j 1
  - cargo test  --all-features --verbose -j 1

notifications:
  irc:
    channels:
    - chat.freenode.net#imag
    template:
    - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"
