language: rust
rust:
  - 1.29.2
  - 1.30.1
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

script:
  - cargo build --all-features --verbose -j 1
  - cargo test  --all-features --verbose -j 1

notifications:
  irc:
    channels:
    - chat.freenode.net#imag
    template:
    - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"
